Attribute VB_Name = "modGlobalConstants"
Option Explicit

Public Const CSIDL_DESKTOP = &H0
Public Const CSIDL_INTERNET = &H1
Public Const CSIDL_PROGRAMS = &H2
Public Const CSIDL_CONTROLS = &H3
Public Const CSIDL_PRINTERS = &H4
Public Const CSIDL_PERSONAL = &H5
Public Const CSIDL_FAVORITES = &H6
Public Const CSIDL_STARTUP = &H7
Public Const CSIDL_RECENT = &H8
Public Const CSIDL_SENDTO = &H9
Public Const CSIDL_BITBUCKET = &HA
Public Const CSIDL_STARTMENU = &HB
Public Const CSIDL_MYDOCUMENTS = &HC
Public Const CSIDL_MYMUSIC = &HD
Public Const CSIDL_MYVIDEO = &HE
Public Const CSIDL_DESKTOPDIRECTORY = &H10
Public Const CSIDL_DRIVES = &H11
Public Const CSIDL_NETWORK = &H12
Public Const CSIDL_NETHOOD = &H13
Public Const CSIDL_FONTS = &H14
Public Const CSIDL_TEMPLATES = &H15
Public Const CSIDL_COMMON_STARTMENU = &H16
Public Const CSIDL_COMMON_PROGRAMS = &H17
Public Const CSIDL_COMMON_STARTUP = &H18
Public Const CSIDL_COMMON_DESKTOP_DIRECTORY = &H19
Public Const CSIDL_APPDATA = &H1A
Public Const CSIDL_PRINTHOOD = &H1B
Public Const CSIDL_LOCAL_APPDATA = &H1C
Public Const CSIDL_ALTSTARTUP = &H1D
Public Const CSIDL_COMMON_ALTSTARTUP = &H1E
Public Const CSIDL_COMMON_FAVORITES = &H1F
Public Const CSIDL_INTERNET_CACHE = &H20
Public Const CSIDL_COOKIES = &H21
Public Const CSIDL_HISTORY = &H22
Public Const CSIDL_COMMON_APPDATA = &H23
Public Const CSIDL_WINDOWS = &H24
Public Const CSIDL_SYSTEM = &H25
Public Const CSIDL_PROGRAM_FILES = &H26
Public Const CSIDL_MYPICTURES = &H27
Public Const CSIDL_PROFILE = &H28
Public Const CSIDL_SYSTEMX86 = &H29
Public Const CSIDL_PROGRAM_FILESX86 = &H2A
Public Const CSIDL_PROGRAM_FILES_COMMON = &H2B
Public Const CSIDL_PROGRAM_FILES_COMMONX86 = &H2C
Public Const CSIDL_COMMON_TEMPLATES = &H2D
Public Const CSIDL_COMMON_DOCUMENTS = &H2E
Public Const CSIDL_COMMON_ADMINTOOLS = &H2F
Public Const CSIDL_ADMINTOOLS = &H30
Public Const CSIDL_CONNECTIONS = &H31
Public Const CSIDL_COMMON_MUSIC = &H35
Public Const CSIDL_COMMON_PICTURES = &H36
Public Const CSIDL_COMMON_VIDEO = &H37
Public Const CSIDL_RESOURCES = &H38
Public Const CSIDL_RESOURCES_LOCALIZED = &H39
Public Const CSIDL_COMMON_OEM_LINKS = &H3A
Public Const CSIDL_CDBURN_AREA = &H3B
Public Const CSIDL_COMPUTERSNEARME = &H3D
Public Const CSIDL_FLAG_PER_USER_INIT = &H800
Public Const CSIDL_FLAG_NO_ALIAS = &H1000
Public Const CSIDL_FLAG_DONT_VERIFY = &H4000
Public Const CSIDL_FLAG_CREATE = &H8000
Public Const CSIDL_FLAG_MASK = &HFF00

Public Const INVALID_HANDLE_VALUE = -1

Public Const FO_MOVE = &H1
Public Const FO_COPY = &H2
Public Const FO_DELETE = &H3
Public Const FO_RENAME = &H4

Public Const FOF_MULTIDESTFILES = &H1
Public Const FOF_CONFIRMMOUSE = &H2
Public Const FOF_SILENT = &H4
Public Const FOF_RENAMEONCOLLISION = &H8
Public Const FOF_NOCONFIRMATION = &H10
Public Const FOF_WANTMAPPINGHANDLE = &H20
Public Const FOF_ALLOWUNDO = &H40
Public Const FOF_FILESONLY = &H80
Public Const FOF_SIMPLEPROGRESS = &H100
Public Const FOF_NOCONFIRMMKDIR = &H200
Public Const FOF_NOERRORUI = &H400
Public Const FOF_NOCOPYSECURITYATTRIBS = &H800
Public Const FOF_NORECURSION = &H1000
Public Const FOF_NO_CONNECTED_ELEMENTS = &H2000
Public Const FOF_WANTNUKEWARNING = &H4000
Public Const FOF_NORECURSEREPARSE = &H8000

Public Const EWX_LOGOFF As Long = &H0
Public Const EWX_SHUTDOWN As Long = &H1
Public Const EWX_REBOOT As Long = &H2
Public Const EWX_FORCE As Long = &H4
Public Const EWX_HIBERNATE = &H5
Public Const EWX_STANDBY = &H6
Public Const EWX_NONE = -11

Public Const WM_USER As Long = &H400
Public Const WM_MYHOOK As Long = WM_USER + 1
Public Const WM_NOTIFY As Long = &H4E
Public Const WM_COMMAND As Long = &H111
Public Const WM_CLOSE As Long = &H10
Public Const WM_PRINTCLIENT = &H318

Public Const WM_MOUSEMOVE = &H200
Public Const WM_LBUTTONDOWN As Long = &H201
Public Const WM_LBUTTONUP As Long = &H202
Public Const WM_LBUTTONDBLCLK As Long = &H203
Public Const WM_MBUTTONDOWN As Long = &H207
Public Const WM_MBUTTONUP As Long = &H208
Public Const WM_MBUTTONDBLCLK As Long = &H209
Public Const WM_RBUTTONDOWN As Long = &H204
Public Const WM_RBUTTONUP As Long = &H205
Public Const WM_RBUTTONDBLCLK As Long = &H206
Public Const WM_MOUSEHOVER = &H2A1
Public Const WM_MOUSELEAVE = &H2A3

Public Const NIN_BALLOONSHOW = (WM_USER + 2)
Public Const NIN_BALLOONHIDE = (WM_USER + 3)
Public Const NIN_BALLOONTIMEOUT = (WM_USER + 4)
Public Const NIN_BALLOONUSERCLICK = (WM_USER + 5)

Public Const GWL_WNDPROC As Long = (-4)
Public Const GWL_HWNDPARENT As Long = (-8)
Public Const GWL_ID As Long = (-12)
Public Const GWL_STYLE As Long = (-16)
Public Const GWL_EXSTYLE As Long = (-20)
Public Const GWL_USERDATA As Long = (-21)

Public Const NIM_ADD As Long = &H0
Public Const NIM_MODIFY As Long = &H1
Public Const NIM_DELETE As Long = &H2
Public Const NIF_ICON As Long = &H2
Public Const NIF_TIP As Long = &H4
Public Const NIF_MESSAGE As Long = &H1
Public Const NIF_INFO = &H10

Public Const NIIF_NONE = &H0
Public Const NIIF_INFO = &H1
Public Const NIIF_WARNING = &H2
Public Const NIIF_ERROR = &H3
Public Const NIIF_GUID = &H5
Public Const NIIF_ICON_MASK = &HF
Public Const NIIF_NOSOUND = &H10

Public Const SHAC_DEFAULT = &H0
Public Const SHAC_FILESYSTEM = &H1
Public Const SHAC_URLHISTORY = &H2
Public Const SHAC_URLMRU = &H4
Public Const SHAC_USETAB = &H8
Public Const SHAC_URLALL = (SHAC_URLHISTORY Or SHAC_URLMRU)
Public Const SHAC_AUTOAPPEND_ON = &H40000000
Public Const SHAC_AUTOAPPEND_OFF = &H80000000

Public Const MCI_CLOSE = &H804&
Public Const MCI_WAIT = &H2&
Public Const MCI_OPEN = &H803&
Public Const MCI_FORMAT_MILLISECONDS = 0
Public Const MCI_SET = &H80D&
Public Const MCI_OPEN_ELEMENT = &H200&
Public Const MCI_SET_TIME_FORMAT = &H400&
Public Const MCI_STOP = &H808&
Public Const MCI_SEEK = &H807&
Public Const MCI_SEEK_TO_START = &H100&
Public Const MCI_PLAY = &H806&
Public Const MCI_NOTIFY = &H1&
Public Const MCI_STATUS_POSITION = &H2&
Public Const MCI_STATUS = &H814&
Public Const MCI_STATUS_ITEM = &H100&
Public Const MCI_STATUS_LENGTH = &H1&
Public Const MCI_TO = &H8&
Public Const MCI_OPEN_TYPE = &H2000&
Public Const MCI_RECORD = &H80F&
Public Const MCI_SAVE = &H813&
Public Const MCI_SAVE_FILE = &H100&
Public Const MCI_MCIAVI_PLAY_WINDOW = &H1000000
Public Const MCI_PAUSE = &H809&
Public Const MCI_DGV_OPEN_PARENT = &H20000
Public Const MCI_DGV_OPEN_WS = &H10000
Public Const MCI_WINDOW = &H841&
Public Const MCI_DGV_WINDOW_STATE = &H40000
Public Const MCI_DGV_STATUS_HWND = &H4001&
Public Const MCI_WHERE = &H843
Public Const MCI_DGV_WHERE_SOURCE = &H20000

Public Const WS_CHILD = &H40000000
Public Const SW_SHOW = 5

Public Const AW_HOR_POSITIVE = &H1
Public Const AW_HOR_NEGATIVE = &H2
Public Const AW_VER_POSITIVE = &H4
Public Const AW_VER_NEGATIVE = &H8
Public Const AW_CENTER = &H10
Public Const AW_HIDE = &H10000
Public Const AW_ACTIVATE = &H20000
Public Const AW_SLIDE = &H40000
Public Const AW_BLEND = &H80000

Public Const ERROR_SUCCESS = 0

Public Const WM_NCDESTROY = &H82

Public Const OLDWNDPROCNAME = "OldWndProc"

Public Const ICC_LISTVIEW_CLASSES = &H1
Public Const ICC_TREEVIEW_CLASSES = &H2
Public Const ICC_BAR_CLASSES = &H4
Public Const ICC_TAB_CLASSES = &H8
Public Const ICC_UPDOWN_CLASS = &H10
Public Const ICC_PROGRESS_CLASS = &H20
Public Const ICC_HOTKEY_CLASS = &H40
Public Const ICC_ANIMATE_CLASS = &H80
Public Const ICC_WIN95_CLASSES = &HFF
Public Const ICC_DATE_CLASSES = &H100
Public Const ICC_USEREX_CLASSES = &H200
Public Const ICC_COOL_CLASSES = &H400
Public Const ICC_INTERNET_CLASSES = &H800
Public Const ICC_PAGESCROLLER_CLASS = 1000
Public Const ICC_NATIVEFNTCTL_CLASS = 2000
Public Const ICC_STANDARD_CLASSES = 4000
Public Const ICC_LINK_CLASS = 8000

Public Const LVM_FIRST = &H1000
Public Const LVM_SETCOLUMNWIDTH = (LVM_FIRST + 30)
Public Const LVSCW_AUTOSIZE_USEHEADER = -2

Public Const OFN_ALLOWMULTISELECT As Long = &H200
Public Const OFN_CREATEPROMPT As Long = &H2000
Public Const OFN_ENABLEHOOK As Long = &H20
Public Const OFN_ENABLETEMPLATE As Long = &H40
Public Const OFN_ENABLETEMPLATEHANDLE As Long = &H80
Public Const OFN_EXPLORER As Long = &H80000
Public Const OFN_EXTENSIONDIFFERENT As Long = &H400
Public Const OFN_FILEMUSTEXIST As Long = &H1000
Public Const OFN_HIDEREADONLY As Long = &H4
Public Const OFN_LONGNAMES As Long = &H200000
Public Const OFN_NOCHANGEDIR As Long = &H8
Public Const OFN_NODEREFERENCELINKS As Long = &H100000
Public Const OFN_NOLONGNAMES As Long = &H40000
Public Const OFN_NONETWORKBUTTON As Long = &H20000
Public Const OFN_NOREADONLYRETURN As Long = &H8000& 'see comments
Public Const OFN_NOTESTFILECREATE As Long = &H10000
Public Const OFN_NOVALIDATE As Long = &H100
Public Const OFN_OVERWRITEPROMPT As Long = &H2
Public Const OFN_PATHMUSTEXIST As Long = &H800
Public Const OFN_READONLY As Long = &H1
Public Const OFN_SHAREAWARE As Long = &H4000
Public Const OFN_SHAREFALLTHROUGH As Long = 2
Public Const OFN_SHAREWARN As Long = 0
Public Const OFN_SHARENOWARN As Long = 1
Public Const OFN_SHOWHELP As Long = &H10
Public Const OFS_MAXPATHNAME As Long = 260

Public Enum EVENT_Constants
  eMouseMove = WM_MOUSEMOVE
  eLeftMouseDown = WM_LBUTTONDOWN
  eLeftMouseUp = WM_LBUTTONUP
  eLeftMouseDblClick = WM_LBUTTONDBLCLK
  eMiddleMouseDown = WM_MBUTTONDOWN
  eMiddleMouseUp = WM_MBUTTONUP
  eMiddleMouseDblClick = WM_MBUTTONDBLCLK
  eRightMouseDown = WM_RBUTTONDOWN
  eRightMouseUp = WM_RBUTTONUP
  eRightMouseDblClick = WM_RBUTTONDBLCLK
  eMouseHover = WM_MOUSEHOVER
  eMouseLeave = WM_MOUSELEAVE
  eBalloonTipClicked = NIN_BALLOONUSERCLICK
  eBalloonTipTimedOut = NIN_BALLOONTIMEOUT
End Enum
